version: "3.7"
services:
  ws:
    build:
      context: Dockerfile.d/ws
      args:
        USER: ${USER:-john.doe}
        UID: ${UID:-0}
        GID: ${GID:-0}
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ${HOME}/.ssh/id_rsa:/home/${USER}/.ssh/id_rsa:ro
      - ws-home:/home
    user: "${UID:-0}:${GID:-0}"
    command:
      - bash
      - -c
      - |
        cargo-make make --makefile tasks/install.toml
volumes:
  ws-home:
    driver: local
