[config]
skip_core_tasks = true
min_version = "0.26.0"

[env]
GIT_REPO_URL = { script = ["git remote get-url origin"] }

[tasks.prepare]
cwd = "${CARGO_MAKE_CURRENT_TASK_INITIAL_MAKEFILE_DIRECTORY}/../"

[tasks.create-directories]
dependencies = [
  "prepare"
]
script = [
'''
mkdir -p "${HOME}/Creations/"
mkdir -p "${HOME}/.go/"
'''
]

[tasks.clone-the-repo]
dependencies = [
  "prepare"
]
condition = { files_not_exist = ["${HOME}/.dotfiles/.git"] }
script = [
'''
git clone ${GIT_REPO_URL} "${HOME}/.dotfiles"
'''
]

[tasks.switch-to-specific-branch]
dependencies = [
  "prepare",
  "clone-the-repo"
]
condition.files_exist = ["${HOME}/.dotfiles/.git"]
condition.env_set = ["GIT_BRANCH"]
script_runner = "zsh"
script = [
'''
if [[ ! -z ${GIT_BRANCH} ]]; then
  cd "${HOME}/.dotfiles"
  git checkout -b ${GIT_BRANCH} origin/${GIT_BRANCH}
fi
'''
]

[tasks.update-the-repo]
dependencies = [
  "prepare",
  "clone-the-repo"
]
condition = { files_exist = ["${HOME}/.dotfiles/.git"] }
script_runner = "zsh"
script = [
'''
cd "${HOME}/.dotfiles"
default_branch=$(git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@')
topic_branch=$(git rev-parse --abbrev-ref HEAD)
if [[ ! -z $default_branch ]] && [[ ! -z $topic_branch ]]; then
  if [[ $default_branch = $topic_branch ]]; then
    git pull --ff-only
  fi
fi
git submodule update --init --recursive
'''
]

[tasks.create-default-symlinks-in-home]
cwd = "${HOME}"
dependencies = [
  "clone-the-repo",
  "update-the-repo"
]
condition = { files_exist = ["${HOME}/.dotfiles"] }
script_runner = "zsh"
script = [
'''
cd "${HOME}"
for f in $(ls -1d .dotfiles/symlinks/home.default/(.|[[:alnum:]])*)
do
  if [[ 'Darwin' == $(uname -s) ]]; then
    ln -fsh $f $(basename $f)
  else
    ln -fs --no-dereference $f $(basename $f)
  fi
done
'''
]

[tasks.create-default-symlinks-in-home-platform-specfic-part.mac]
cwd = "${HOME}"
dependencies = [
  "clone-the-repo",
  "update-the-repo",
  "create-default-symlinks-in-home"
]
condition = { files_exist = ["${HOME}/.dotfiles"] }
script_runner = "zsh"
script = [
'''
cd "${HOME}"
for f in $(ls -1d .dotfiles/symlinks/home.macos/(.|[[:alnum:]])*)
do
  ln -fsh $f $(basename $f)
done
'''
]

[tasks.create-app-symlinks]
dependencies = [
  "clone-the-repo",
  "update-the-repo",
  "create-app-symlinks-adobe-cc"
]

[tasks.create-app-symlinks-adobe-cc.mac]
dependencies = [
  "clone-the-repo",
  "update-the-repo"
]
condition.files_exist = ["${HOME}/.dotfiles"]
condition.files_not_exist = ["${HOME}/Library/Preferences/Adobe Photoshop 2020 Settings"]
script = [
'''
mkdir -p "${HOME}/Library/Preferences/Adobe Photoshop 2020 Settings"
cd "${HOME}/Library/Preferences/Adobe Photoshop 2020 Settings"
ln -s "~/.dotfiles/symlinks/app.adobe-cc/Adobe Photoshop 2020 Settings/New Doc Sizes.json" .
'''
]

[tasks.set-the-login-shell-to-zsh]
dependencies = [
  "disable-sudo-timeout"
]
script = [
'''
sudo chsh -s /bin/zsh $USER
'''
]

[tasks.install-common-part]
dependencies = [
  "clone-the-repo",
  "switch-to-specific-branch",
  "update-the-repo",
  "create-default-symlinks-in-home",
  "create-default-symlinks-in-home-platform-specfic-part",
  "create-app-symlinks",
  "set-the-login-shell-to-zsh"
]
