extend = [{ path = ".install-common.toml" }, { path = ".install-mac.toml" }, { path = ".install-linux.toml" }]

[config]
skip_core_tasks = true
min_version = "0.26.0"
# on_error_task = "reset-sudo-timeout"

[tasks.disable-sudo-timeout]
script = [
'''
sudo sh -c "echo 'Defaults timestamp_timeout=-1' > /etc/sudoers.d/disable_timestamp_timeout"
'''
]

[tasks.reset-sudo-timeout]
script = [
'''
sudo rm -f /etc/sudoers.d/disable_timestamp_timeout
'''
]

[tasks.default]
dependencies = [
  "disable-sudo-timeout",
  "install-common-part",
  "install-platform-specfic-part",
  "reset-sudo-timeout"
]
